"""PDF invoice generation using ReportLab."""
import io

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.pdfgen import canvas


def _rupees(paise: int) -> str:
    return f"Rs. {paise / 100:,.2f}"


def generate_invoice_pdf(invoice: dict, salon: dict, customer: dict) -> bytes:
    """Render a one-page invoice PDF and return it as bytes."""
    buf = io.BytesIO()
    c = canvas.Canvas(buf, pagesize=A4)
    width, height = A4

    left = 20 * mm
    top = height - 25 * mm

    # Header
    c.setFillColor(colors.HexColor("#1f2937"))
    c.setFont("Helvetica-Bold", 22)
    c.drawString(left, top, salon.get("salon_name", "Salon"))

    c.setFont("Helvetica", 10)
    c.setFillColor(colors.HexColor("#6b7280"))
    c.drawString(left, top - 7 * mm, f"Owner: {salon.get('owner_name', '')}")
    if salon.get("upi_id"):
        c.drawString(left, top - 12 * mm, f"UPI: {salon['upi_id']}")

    c.setFont("Helvetica-Bold", 16)
    c.setFillColor(colors.HexColor("#111827"))
    c.drawRightString(width - left, top, "INVOICE")
    c.setFont("Helvetica", 9)
    c.setFillColor(colors.HexColor("#6b7280"))
    c.drawRightString(width - left, top - 7 * mm, f"No: INV-{str(invoice.get('id', ''))[:8]}")

    # Divider
    c.setStrokeColor(colors.HexColor("#e5e7eb"))
    c.setLineWidth(1)
    c.line(left, top - 18 * mm, width - left, top - 18 * mm)

    # Bill-to
    y = top - 30 * mm
    c.setFont("Helvetica-Bold", 11)
    c.setFillColor(colors.HexColor("#111827"))
    c.drawString(left, y, "Bill To")
    c.setFont("Helvetica", 10)
    c.setFillColor(colors.HexColor("#374151"))
    c.drawString(left, y - 6 * mm, customer.get("customer_name", "Customer"))
    if customer.get("phone"):
        c.drawString(left, y - 11 * mm, f"+91 {customer['phone']}")

    # Line item table
    y -= 28 * mm
    c.setFillColor(colors.HexColor("#f3f4f6"))
    c.rect(left, y, width - 2 * left, 9 * mm, fill=1, stroke=0)
    c.setFillColor(colors.HexColor("#111827"))
    c.setFont("Helvetica-Bold", 10)
    c.drawString(left + 3 * mm, y + 2.5 * mm, "Description")
    c.drawRightString(width - left - 3 * mm, y + 2.5 * mm, "Amount")

    y -= 10 * mm
    c.setFont("Helvetica", 10)
    c.setFillColor(colors.HexColor("#374151"))
    description = invoice.get("description") or "Salon service"
    c.drawString(left + 3 * mm, y, description)
    c.drawRightString(width - left - 3 * mm, y, _rupees(invoice.get("amount", 0)))

    # Total
    y -= 12 * mm
    c.setStrokeColor(colors.HexColor("#e5e7eb"))
    c.line(left, y + 6 * mm, width - left, y + 6 * mm)
    c.setFont("Helvetica-Bold", 12)
    c.setFillColor(colors.HexColor("#111827"))
    c.drawString(left + 3 * mm, y, "Total")
    c.drawRightString(width - left - 3 * mm, y, _rupees(invoice.get("amount", 0)))

    # Status
    y -= 12 * mm
    status = (invoice.get("payment_status") or "unpaid").upper()
    c.setFont("Helvetica-Bold", 11)
    c.setFillColor(
        colors.HexColor("#059669") if status == "PAID" else colors.HexColor("#dc2626")
    )
    c.drawString(left + 3 * mm, y, f"Status: {status}")

    # Footer
    c.setFont("Helvetica", 8)
    c.setFillColor(colors.HexColor("#9ca3af"))
    c.drawCentredString(width / 2, 18 * mm, "Generated by Ping - WhatsApp Salon Management")

    c.showPage()
    c.save()
    return buf.getvalue()
